<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="LocalBuildProperties_example.props" Condition="!Exists('LocalBuildProperties.props')" />
  <Import Project="LocalBuildProperties.props" Condition="Exists('LocalBuildProperties.props')" />

  <PropertyGroup>
    <AssemblyName>HollowKnightLocal8</AssemblyName>
    <RootNamespace>KO.HollowKnight8</RootNamespace>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PathMap Condition="'$(Configuration)' == 'Release'">$(MSBuildProjectDirectory)=source</PathMap>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="src\Local8.RoomWaitFrame" />
    <EmbeddedResource Include="src\Local8.RoomWaitFrame" LogicalName="Local8.RoomWaitFrame" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp"><HintPath>$(References)\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MMHOOK_Assembly-CSharp"><HintPath>$(References)\MMHOOK_Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="PlayMaker"><HintPath>$(References)\PlayMaker.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MMHOOK_PlayMaker"><HintPath>$(References)\MMHOOK_PlayMaker.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="InControl"><HintPath>$(References)\InControl.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(References)\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(References)\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AudioModule"><HintPath>$(References)\UnityEngine.AudioModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(References)\UnityEngine.ImageConversionModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(References)\UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>$(References)\UnityEngine.InputLegacyModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ParticleSystemModule"><HintPath>$(References)\UnityEngine.ParticleSystemModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.Physics2DModule"><HintPath>$(References)\UnityEngine.Physics2DModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(References)\UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(References)\UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(References)\UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(References)\Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
